-- nvim-tree/nvim-tree.lua
-- require("nvim-tree").setup({
--     sync_root_with_cwd = true,
--     actions = {
--         change_dir = {
--             enable = false,
--         },
--     },
--     view = {
--         mappings = {
--             list = {
--                 { key = "u", action = "dir_up" },
--             },
--         },
--         signcolumn = "auto",                          -- remove left most empty column
--     },
--     renderer = {
--         icons = {
--             show = {
--                 file = false,
--                 folder = false,
--                 folder_arrow = true,
--                 git = false,
--                 modified = false,
--             },
--             symlink_arrow = " -> ",
--             glyphs = {
--                 bookmark = "*",
--                 folder = {
--                     arrow_closed = "▸",
--                     arrow_open = "▾",
--                 },
--             },
--         },
--     },
-- })
-- keymap("n", "<leader>e", ":NvimTreeToggle<cr>", keymap_opts)

