set -g default-command "${SHELL}"
set -g default-terminal "xterm-256color"
set -as terminal-overrides ",xterm-256color:RGB"
setw -g mode-keys vi
set -s set-clipboard on

# Use h,j,k,l to switch pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
