# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$conda\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character
"""

# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = "\ue725 "

[conda]
ignore_base = false
detect_env_vars = ["CONDA_DEFAULT_ENV"]
format = 'via [$symbol$environment]($style) '
