require("config.settings")
require("config.keymaps")
require("config.lazy")
require("config.clipboard")
require("config.indentation")
require("config.diagnostic")
require("config.with_buf_cwd")
require("config.rename_under_cursor")
